# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-23 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_d_models_stock_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='cover',
            field=models.TextField(default='null=True'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='link',
            field=models.TextField(default='null=True'),
            preserve_default=False,
        ),
    ]
